In [1]:
import io
import pandas as pd

# URL do arquivo JSON contendo os dados de hospedagem
url = 'https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/dados_hospedagem.json'

# Lê o arquivo JSON da URL
# Utiliza io.StringIO para tratar a URL como um arquivo em memória
# Converte o JSON lido para DataFrame, depois para JSON string e lê novamente para garantir o formato correto
dados = pd.read_json(io.StringIO(pd.read_json(url).to_json()))
dados = pd.json_normalize(dados['info_moveis']) #SELECIONAR A COLUNA A NORMALIZAR
# Mostra as primeiras 5 linhas do DataFrame
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"

---

### Para saber mais: descrição dos dados

Antes de analisar qualquer conjunto de dados, é importante entender o que cada coluna representa, para que possamos estudá-lo e tratá-lo adequadamente.

No arquivo **dados\_hospedagem.json**, as colunas trazem as seguintes informações:

* **avaliacao\_geral**: média das notas da hospedagem.
* **experiencia\_local**: experiências oferecidas no imóvel.
* **max\_hospedes**: capacidade máxima de hóspedes.
* **descricao\_local**: descrição do imóvel.
* **descricao\_vizinhanca**: descrição da vizinhança.
* **quantidade\_banheiros**: número de banheiros disponíveis.
* **quantidade\_quartos**: número de quartos disponíveis.
* **quantidade\_camas**: número de camas disponíveis.
* **modelo\_cama**: tipo de cama oferecido.
* **comodidades**: facilidades disponíveis no imóvel.
* **taxa\_deposito**: depósito mínimo de segurança.
* **taxa\_limpeza**: valor cobrado pelo serviço de limpeza.
* **preco**: preço base da diária do imóvel.

---

# Desagrupar Dados

##Coletando os nomes das colunas

`Método .explode()`

In [2]:
colunas = list(dados.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [3]:
#dados a serem separados em linhas
dados = dados.explode(colunas[3:]) #slice - partição da lista
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

##Resetando os índices para ordenar os dados

`.reset_index()`

In [4]:
# Reseta o índice do DataFrame e remove o índice antigo.
# inplace=True modifica o DataFrame diretamente sem retornar um novo.
# drop=True impede que o índice antigo seja adicionado como uma nova coluna.
dados.reset_index(inplace=True, drop=True)
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00

#Verificando os tipos de dados

In [5]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

Perceba que a coluna "Dtype" traz todos os dados como sendo do tipo object. Há três possibilidades para que um dado seja identificado assim:

1) Por termos tipos diferentes de dados em uma mesma coluna;

2) Quando os dados possuem um tipo específico que não foi identificado na leitura do Pandas;

3) Todos os tipos são strings.

##Convertendo dados numéricos

In [6]:
import  numpy as np

###Tratando dados numéricos: convertendo para tipo inteiro

`.astype()`

In [7]:
#Converter colunas para um tipo específico de dado
dados['max_hospedes'].astype(np.int64) #inteiro com precisão de 64 bits.

0       1
1       1
2       1
3       1
4       1
       ..
3813    8
3814    8
3815    8
3816    9
3817    9
Name: max_hospedes, Length: 3818, dtype: int64

In [8]:
dados['max_hospedes'] = dados['max_hospedes'].astype(np.int64)

In [9]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

### Aplicando em mais de uma coluna

In [10]:
col_numericas = ['quantidade_banheiros','quantidade_quartos','quantidade_camas']

In [11]:
dados[col_numericas] = dados[col_numericas].astype(np.int64)

In [12]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

## Tratando dados numéricos: convertendo para tipo float

In [13]:
dados['avaliacao_geral'] = dados['avaliacao_geral'].astype(np.float64)

In [14]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [15]:
#dados['preco'] = dados['preco'].astype(np.float64)

Obtemos um erro, porque não é possível aplicar a conversão em dados que contenham o caractere de cifrão.Sendo assim, precisamos, primeiros, tratar esses dados.

---

### Para saber mais: precisão de valores numéricos

Ao lidar com grandes volumes de dados e pouca memória disponível, é comum utilizar tipos de dados mais compactos. Porém, é essencial garantir que essa escolha não comprometa a precisão dos resultados.

#### Bits e Bytes

* **Bit**: menor unidade de informação digital (0 ou 1).
* **Byte**: conjunto de 8 bits.

#### Tipos de inteiros (int)

* **int64**: utiliza 8 bytes (64 bits), representando números de
  **-9.223.372.036.854.775.808 a 9.223.372.036.854.775.807**.
* **int32**: utiliza 4 bytes (32 bits), representando números de
  **-2.147.483.648 a 2.147.483.647**.
* Outros tipos (mais compactos, mas com limites menores):

| Tipo  | Bits | Valor mínimo               | Valor máximo              |
| ----- | ---- | -------------------------- | ------------------------- |
| int8  | 8    | -128                       | 127                       |
| int16 | 16   | -32.768                    | 32.767                    |
| int32 | 32   | -2.147.483.648             | 2.147.483.647             |
| int64 | 64   | -9.223.372.036.854.775.808 | 9.223.372.036.854.775.807 |

**Dica:** use o menor tipo que seja suficiente para representar seus dados — por exemplo, `int32` para valores pequenos, `int64` para números científicos ou muito grandes.

#### Tipos de ponto flutuante (float)

* **float64**: 64 bits, até **15 dígitos de precisão**.
* **float32**: 32 bits, até **7 dígitos de precisão**.

Assim como nos inteiros, a escolha depende do equilíbrio entre **precisão** e **uso de memória**.

---

##Números em strings

In [16]:
dados['preco']

0       $110.00
1        $45.00
2        $55.00
3        $52.00
4        $85.00
         ...
3813    $299.00
3814    $199.00
3815    $400.00
3816    $250.00
3817    $350.00
Name: preco, Length: 3818, dtype: object

`aply()`

.apply() com lambda, que aplica uma função específica a cada elemento, no caso, a remoção dos caracteres.

In [17]:
dados['preco'].apply(lambda x: x.replace('$', '').replace(',','').strip())

0       110.00
1        45.00
2        55.00
3        52.00
4        85.00
         ...
3813    299.00
3814    199.00
3815    400.00
3816    250.00
3817    350.00
Name: preco, Length: 3818, dtype: object

In [18]:
dados['preco'] = dados['preco'].apply(lambda x: x.replace('$', '').replace(',','').strip())
# strip() remove, por padrão, espaços em branco do início e do fim da string.
# Se um argumento for passado, remove os caracteres especificados.

###Usando .astype() depois do tratamento

In [19]:
dados['preco'] = dados['preco'].astype(np.float64)

In [20]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [21]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.0

###Transformação em múltiplas colunas
####Separar as duas colunas em um dataframe

In [22]:
dados[['taxa_deposito','taxa_limpeza']]

     taxa_deposito taxa_limpeza
0               $0           $0
1               $0           $0
2               $0           $0
3               $0       $20.00
4               $0       $15.00
...            ...          ...
3813     $1,000.00      $178.00
3814            $0       $99.00
3815            $0           $0
3816     $1,000.00      $150.00
3817       $500.00           $0

[3818 rows x 2 columns]

`.applymap()`

In [23]:
#dados[['taxa_deposito','taxa_limpeza']].applymap(lambda x: float(x.replace('$', '').replace(',','').strip()))
#Forma antiga, desatualizada

>O map em versões anteriores era utilizado apenas em uma Series (coluna única), mas em versões mais recentes do Pandas, o comportamento desse método foi expandido para também funcionar com DataFrames, aplicando a função elemento a elemento em todas as células, de forma semelhante ao que applymap fazia.

In [24]:
dados[['taxa_deposito','taxa_limpeza']] = dados[['taxa_deposito','taxa_limpeza']].map(
    lambda x: float(x.replace('$', '').replace(',','').strip()))

###Transformar valores para float

In [25]:
dados[['taxa_deposito','taxa_limpeza']] = dados[
    ['taxa_deposito','taxa_limpeza']].astype(np.float64)

In [26]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

In [27]:
dados.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0

#Exercício: trabalhando em outros contextos

In [28]:
url_2 = 'https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/dados_vendas_clientes.json'
url_3 = 'https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/dados_locacao_imoveis.json'
dados_vendas = pd.read_json(io.StringIO(pd.read_json(url_2).to_json()))
dados_locacao = pd.read_json(io.StringIO(pd.read_json(url_3).to_json()))
dados_vendas = pd.json_normalize(dados_vendas['dados_vendas'])
dados_locacao = pd.json_normalize(dados_locacao['dados_locacao'])

##Etapa 2
*  Projeto desafio 1: vendas online

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, o novo desafio do projeto 1 será dividido em algumas metas:

*  Remover os dados em listas dentro do DataFrame;
*  Verificar os tipos de dados;
*  Identificar colunas numéricas;
*  Transformar a coluna numérica para o tipo numérico.

In [29]:
dados_vendas.head()

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [30]:
colunas_vendas = list(dados_vendas.columns)
colunas_vendas

['Data de venda', 'Cliente', 'Valor da compra']

In [31]:
dados_vendas = dados_vendas.explode(colunas_vendas[1:])
dados_vendas = dados_vendas.reset_index(drop=True)
dados_vendas.head()

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
1    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
2    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
3    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
4    07/06/2022  Isabely JOanes 738       R$ 825,31

In [32]:
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 612.0+ bytes

In [33]:
dados_vendas ['Valor da compra']

0      R$ 836,5
1     R$ 573,33
2      R$ 392,8
3     R$ 512,34
4     R$ 825,31
5     R$ 168,07
6     R$ 339,18
7     R$ 314,69
8     R$ 682,05
9     R$ 386,34
10    R$ 622,65
11    R$ 630,79
12     R$ 390,3
13    R$ 759,16
14    R$ 334,47
15    R$ 678,78
16    R$ 314,24
17    R$ 311,15
18    R$ 899,16
19    R$ 885,24
Name: Valor da compra, dtype: object

In [34]:
dados_vendas['Valor da compra'] = dados_vendas[
    'Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',','.').strip())
dados_vendas['Valor da compra'] = dados_vendas['Valor da compra'].astype(np.float64)
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

*  Projeto desafio 2: administração de condomínios

Lemos a base de dados no desafio anterior, agora podemos avançar nas transformações desses dados. Então, da mesma forma que o projeto 1, o desafio do projeto 2 está listado em algumas metas:

*  Remover os dados em listas dentro do DataFrame;
*  Verificar os tipos de dados;
*  Identificar colunas numéricas;
*  Transformar a coluna numérica para o tipo numérico.

In [35]:
dados_locacao.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"

In [36]:
colunas_locacao = list(dados_locacao.columns)
colunas_locacao

['apartamento',
 'datas_combinadas_pagamento',
 'datas_de_pagamento',
 'valor_aluguel']

In [37]:
dados_locacao = dados_locacao.explode(colunas_locacao[1:])
dados_locacao = dados_locacao.reset_index(drop=True)
dados_locacao.head()

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
1,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
2,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
3,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
4,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"

In [38]:
dados_locacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [41]:
dados_locacao['valor_aluguel'] = dados_locacao[
    'valor_aluguel'].apply(lambda x : x.replace('$','').replace(',','.').replace(' reais','').strip())
dados_locacao ['valor_aluguel'] = dados_locacao['valor_aluguel'].astype(np.float64)
dados_locacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.1+ KB