## Leitura CSV

In [1]:
import pandas as pd

In [2]:
url = 'https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/superstore_data.csv'
superstore_data = pd.read_csv(url, sep=',')
superstore_data.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

In [3]:
url_2 = 'https://raw.githubusercontent.com/YuriArduino/Estudos_Pandas/refs/heads/data-tests/superstore_data_ponto_virgula.csv'
superstore_data_2 = pd.read_csv(url_2, sep=';')
superstore_data_2.head()

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835.0,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091.0,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267.0,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474.0,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474.0,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0


# Erro de encoding ao ler CSV no Pandas

Ao tentar ler um arquivo CSV com Pandas, pode surgir o erro:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte ...
```

Isso acontece quando o Pandas não consegue interpretar caracteres do arquivo devido à diferença de codificação. O padrão é **UTF-8**, mas arquivos podem estar em outra codificação, como **ISO-8859-1**.

---

## Detectando a codificação do arquivo com chardet

A biblioteca `chardet` é usada para **detectar a codificação de arquivos de texto**. Ela analisa os bytes do arquivo e retorna a codificação mais provável, sem alterar o conteúdo.

```python
import chardet

with open('/*.csv', 'rb') as file:
    resultado = chardet.detect(file.read())

print(resultado)
```

O resultado é um dicionário indicando:

* `'encoding'`: codificação mais provável
* `'confidence'`: confiança da detecção (0 a 1)
* `'language'`: linguagem associada (opcional)

Exemplo de saída:

```python
{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}
```

---

## Lendo o CSV com a codificação correta

Depois de identificar a codificação, especifique-a ao carregar o arquivo no Pandas:

```python
df = pd.read_csv('/content/dados.csv', encoding='ISO-8859-1')
```

Assim, o Pandas consegue ler o arquivo sem gerar erros de encoding.

---

#Parâmetros

`nrow()s`: Este é um parâmetro que você usa com a função pd.read_csv(). Ele serve para especificar quantas linhas do arquivo CSV você quer ler. É útil quando o arquivo é muito grande e você só precisa carregar uma parte dele para ter uma ideia do conteúdo, economizando memória e tempo de processamento.

`head()`: Este é um método que você usa em um DataFrame (que já foi carregado na memória). Ele serve para exibir as primeiras N linhas do DataFrame. Por padrão, ele mostra as 5 primeiras linhas, mas você pode especificar outro número dentro dos parênteses, como em df.head(10). É usado para visualizar o início do DataFrame depois que ele já foi criado.

`nrows()`

In [4]:
# Quando temos um DataFrame muito grande e queremos apenas ter uma
# visualização geral do conteúdo.
dados_primeiras_linhas = pd.read_csv(url,nrows=5)
dados_primeiras_linhas

,Id,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,Response,Complain
0,1826,1970,Graduation,Divorced,84835,0,0,6/16/2014,0,189,...,111,189,218,1,4,4,6,1,1,0
1,1,1961,Graduation,Single,57091,0,0,6/15/2014,0,464,...,7,0,37,1,7,3,7,5,1,0
2,10476,1958,Graduation,Married,67267,0,1,5/13/2014,0,134,...,15,2,30,1,3,2,5,2,0,0
3,1386,1967,Graduation,Together,32474,1,1,11/5/2014,0,10,...,0,0,0,1,1,0,2,7,0,0
4,5371,1989,Graduation,Single,21474,1,0,8/4/2014,0,6,...,11,0,34,2,3,1,2,7,1,0

`usecols`

In [5]:
#Parâmetro que consegue mostrar apenas algumas colunas.
dados_selecao = pd.read_csv(url, usecols=['Id', 'Year_Birth', 'Income'])
dados_selecao

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

In [6]:
#Podemos usar o mesmo padrão, contudo usando o Id
dados_selecao = pd.read_csv(url, usecols=[0,1,4])
dados_selecao

         Id  Year_Birth   Income
0      1826        1970  84835.0
1         1        1961  57091.0
2     10476        1958  67267.0
3      1386        1967  32474.0
4      5371        1989  21474.0
...     ...         ...      ...
2235  10142        1976  66476.0
2236   5263        1977  31056.0
2237     22        1976  46310.0
2238    528        1978  65819.0
2239   4070        1969  94871.0

[2240 rows x 3 columns]

#Função to_csv()

`Salvar Data Frame`

In [7]:
dados_selecao.to_csv('clientes_mercado.csv')

`Ler Csv: `

In [8]:
clientes_mercado = pd.read_csv('/content/clientes_mercado.csv')
clientes_mercado.head(5)

   Unnamed: 0     Id  Year_Birth   Income
0           0   1826        1970  84835.0
1           1      1        1961  57091.0
2           2  10476        1958  67267.0
3           3   1386        1967  32474.0
4           4   5371        1989  21474.0

`Remover o index: `

In [9]:
dados_selecao.to_csv('dados_mercado.csv', index=False)
clientes_mercado_sem_index = pd.read_csv('/content/dados_mercado.csv')
clientes_mercado_sem_index.head(5)

      Id  Year_Birth   Income
0   1826        1970  84835.0
1      1        1961  57091.0
2  10476        1958  67267.0
3   1386        1967  32474.0
4   5371        1989  21474.0

##Exercícios


 Temos um arquivo no formato CSV, que foi obtido na página Informações de Saúde (TABNET) - DATASUS. Este arquivo contém os gastos hospitalares públicos de cada uma das Unidades da Federação brasileira no período de janeiro de 2008 a março de 2021.

1. Verifique se o arquivo CSV está separado por vírgula ou ponto e vírgula.

In [20]:
pd.read_csv('/content/dados_sus.csv', nrows=5)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 56: invalid continuation byte

In [21]:
import chardet

with open('/content/dados_sus.csv', 'rb') as file:
    resultado = chardet.detect(file.read())

print(resultado)

{'encoding': 'ISO-8859-1', 'confidence': 0.73, 'language': ''}

2. A codificação do arquivo é ISO-8859-1.

In [23]:
pd.read_csv('/content/dados_sus.csv', nrows=5, encoding='ISO-8859-1', sep=';')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 4, saw 161

3. As três primeiras linhas linhas do arquivo podem ser desconsideradas, pois o cabeçalho só começa na quarta linha.

In [36]:
pd.read_csv('/content/dados_sus.csv', nrows=5, encoding='ISO-8859-1', sep=';', skiprows=3)

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"

In [37]:
pd.read_csv('/content/dados_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3)

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"
28,Fonte: Ministério da Saúde - Sistema de Infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Dados referentes aos últimos seis meses, suje...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"A partir do processamento de junho de 2012, h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Até maio de 2012 estas informações estão...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,"De junho de 2012 a outubro de 2015, estã...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"A partir de novembro de 2015, estão disp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

4. As 9 últimas linhas também podem ser desconsideradas, pois são apenas informações sobre onde os dados foram obtidos.

5. Para deletar as últimas linhas é necessário adicionar o parâmetro engine='python'.

In [43]:
pd.read_csv('/content/dados_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3).tail(7)

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
28,Fonte: Ministério da Saúde - Sistema de Infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Notas:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"Dados referentes aos últimos seis meses, suje...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"A partir do processamento de junho de 2012, h...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Até maio de 2012 estas informações estão...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,"De junho de 2012 a outubro de 2015, estã...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"A partir de novembro de 2015, estão disp...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# Lê o arquivo CSV
# encoding='ISO-8859-1': especifica a codificação do arquivo para que caracteres especiais sejam lidos corretamente.
# sep=';': especifica que o delimitador entre as colunas é ponto e vírgula.
# skiprows=3: pula as 3 primeiras linhas do arquivo, que não fazem parte dos dados.
# skipfooter=9: pula as 9 últimas linhas do arquivo, que são informações adicionais.
# engine='python': necessário para usar o parâmetro skipfooter.

pd.read_csv('/content/dados_sus.csv', encoding='ISO-8859-1', sep=';', skiprows=3, skipfooter=9, engine='python')

,Unidade da Federação,2008/Jan,2008/Fev,2008/Mar,2008/Abr,2008/Mai,2008/Jun,2008/Jul,2008/Ago,2008/Set,...,2020/Jul,2020/Ago,2020/Set,2020/Out,2020/Nov,2020/Dez,2021/Jan,2021/Fev,2021/Mar,Total
0,Rondônia,"1388528,39","2931283,42","1541682,52","1525314,96","1645953,84","1406150,68","3065279,01","3231494,61","3117178,63",...,"11824687,13","11733307,76","10201985,14","7955139,45","9357946,29","8880836,55","9266014,59","7730597,04","11023309,47","996411254,68"
1,Acre,"902416,00","1497206,26","1794028,48","1730469,42","1819443,92","1828496,00","2511754,59","2089107,14","2275708,53",...,"3915193,20","3640142,82","3391242,21","4044321,44","3276590,10","3696997,31","3715723,12","3538427,92","4077045,92","450048530,47"
2,Amazonas,"4735529,42","7118990,57","8196635,49","8259378,42","7831399,90","8477273,62","9368858,72","9352532,70","9363099,35",...,"19769460,14","18059931,43","17841015,63","16408315,10","19895617,91","17765167,69","21430289,17","25917134,55","22032176,22","1917247936,05"
3,Roraima,"657889,53","777939,31","718688,03","839994,39","862347,96","832440,66","996693,09","894271,18","910424,17",...,"3015488,30","2826486,18","2928043,91","3090313,73","3621031,05","3454460,94","3266928,47","3519773,73","3985530,08","328876965,09"
4,Pará,"18864744,11","19553758,20","21937342,70","20842829,69","23249952,88","23240687,56","24002223,56","23341218,03","25172261,32",...,"40804126,43","44385715,88","36820249,47","36965931,34","39004315,80","38015145,79","38354682,46","37688314,23","33276392,89","4705309002,29"
5,Amapá,"1120973,34","1268740,33","974651,24","1141137,32","866346,18","1440978,95","1426659,48","1475551,38","1651341,43",...,"3253399,45","2946398,44","2416019,23","2203732,04","2218532,26","2566919,60","2802886,34","2817849,31","3188210,98","309860092,59"
6,Tocantins,"3441592,69","4985688,85","6205612,60","4984482,09","5511002,46","4927934,22","5445602,28","5413710,38","5596669,50",...,"9155572,36","8390267,72","8729632,49","7770885,66","527840,46","675277,05","419553,49","319160,87","1357751,33","1020028272,64"
7,Maranhão,"10723506,39","13559679,41","13985142,36","14809416,46","14505727,38","14908091,32","15784899,40","15195312,89","14951277,75",...,"35473489,49","32219037,29","30077152,72","33200778,47","31942670,33","30783403,58","30738750,31","30924484,99","39663677,48","3871069498,04"
8,Piauí,"7985142,43","10079928,25","10298372,45","10775976,33","10398360,88","10528253,88","11040107,92","10549176,40","10899198,97",...,"19908573,27","25663537,49","20230782,72","22389215,72","18911604,50","20883972,79","22689390,32","19400269,01","20018325,75","2280888802,74"
9,Ceará,"15539821,90","25735101,55","28724625,75","30676457,06","30604453,47","31272395,18","30925391,36","27851438,72","30362719,90",...,"56019506,33","61719491,69","56625919,77","59074596,33","56916499,66","50849353,22","52078218,88","53171253,41","62079618,54","6591836650,18"
10,Rio Grande do Norte,"5947814,08","9509755,83","10352238,59","10855108,50","11160168,19","10475071,38","11386349,96","10640817,47","11336030,28",...,"26337808,77","27579658,62","27721340,38","26048003,33","24737052,09","23846816,35","28044464,51","26317613,74","23306498,68","2660122027,15"
11,Paraíba,"10723002,45","11386274,47","12053643,87","12653528,76","12215107,11","12256928,49","12755413,77","12872578,37","12558296,11",...,"27294311,05","23288213,79","19480481,07","19988426,94","18418075,59","18099514,43","19524543,63","21302722,77","25750897,89","2614919044,63"
12,Pernambuco,"14393949,89","24181400,95","29991302,71","34806197,97","32147987,35","32239094,89","32685640,76","35457038,66","33668261,46",...,"74914677,43","77232881,01","71715677,42","66555628,25","78904176,21","70978052,15","83846222,44","75562664,69","83870992,73","8581189975,91"
13,Alagoas,"6243726,32","8376622,16","8408336,22","9090794,82","9338771,45","10068210,08","9887061,61","9373432,00","9563580,50",...,"18453860,49","19995280,39","18185986,17","18871513,02","18597375,56","17805273,37","17543184,88","18526929,38","22118639,05","2236415402,51"
14,Sergipe,"2780750,11","3676483,16","5051473,61","5046063,36","4741151,56","5401259,63","5521904,44","5238398,50","5187912,19",...,"10313262,56","11404646,48","10741986,60","12278300,58","12264609,05","11454427,82","12060864,70","13003816,54","13321494,41","1215853015,00"
15,Bahia,"21211522,47","28189304,95","34181483,52","39026934,13","42949566,82","47025972,04","47481695,17","46931248,28","44883379,31",...,"84204991,86","83478081,57","80540324,01","81250834,02","86257814,00","85871122,17","79961693,17","81992571,15","98746333,07","9791541570,52"
16,Minas Gerais,"45671659,76","70194037,10","79231336,95","77136537,58","80554440,63","94758522,83","85360064,11","84722528,10","84601757,95",...,"165759955,94","171048093,95","175439696,53","178279152,74","175253226,91","172509435,62","174722161,98","177270694,34","200471045,07","20418737536,66"
17,Espírito Santo,"5456723,98","9102212,86","10249595,97","11253833,56","10198619,17","13364258,29","13035374,08","12588595,77","12727433,30",...,"33474963,98","32364742,01","38569356,14","35748380,19","32030401,25","33674687,78","39642483,39","40243896,20","45490499,45","3405850698,58"
18,Rio de Janeiro,"23025258,52","28394310,93","44567062,94","44054604,82","44911021,15","48056212,24","49872379,35","50912706,60","49270352,76",...,"99331352,01","96339615,99","88305239,94","86995649,35","86776500,97","90416725,95","94179674,42","85583557,95","106837295,81","10337391164,52"
19,São Paulo,"91678473,48","148677526,82","156087269,23","161227125,43","187119397,64","187291126,07","194398399,48","184854516,35","188636359,55",...,"367648996,72","349900969,68","354117254,42","345733068,79","335084865,66","330489045,98","355149525,60","348827130,99","392946147,42","41396604304,13"
20,Paraná,"38266347,46","55384670,52","53801318,85","52460306,69","54419620,71","57811688,48","58094241,83","56982774,90","57549082,26",...,"109720663,59","129529222,48","122702263,26","129647873,97","126859051,02","120037066,76","122122779,12","132622112,72","140264608,52","14681514706,67"
21,Santa Catarina,"16504913,45","25651429,11","26743524,89","27181488,26","26845308,18","29909762,04","30789135,84","31250854,33","30019676,93",...,"61267297,89","65467585,93","71781494,82","69414431,71","68460616,55","70333079,37","71970474,56","74337524,03","81376630,57","7835011163,40"
22,Rio Grande do Sul,"30931325,46","57363420,01","51547794,07","56673338,49","48397733,07","52413429,62","56636376,98","56113054,70","55356224,30",...,"100579287,65","102609965,59","104401019,54","117458292,46","108853890,98","111760506,80","119992419,94","111797400,70","130155185,16","12764391179,92"
23,Mato Grosso do Sul,"5377392,11","7002472,61","8423933,19","8797487,68","9770421,80","10905392,18","10249299,82","9671553,45","10218511,05",...,"18858844,44","19877080,68","19247894,51","19497210,85","22023126,25","19629591,55","21693311,15","24337295,63","25168195,34","2324525096,33"
24,Mato Grosso,"4795299,01","8684882,23","7886243,14","8794109,79","9231645,40","10221763,77","9163314,28","9243148,81","9052354,89",...,"16834650,98","19704915,36","20746227,60","22727405,20","20506039,58","19583803,46","19120141,68","18349376,92","19611032,61","2180119781,15"
25,Goiás,"15310637,29","22258668,68","21442515,75","20921212,45","21615970,67","18270043,87","20540517,13","20650730,67","20868443,56",...,"40606222,82","46229357,10","44889588,33","45529496,23","43037600,45","44147353,21","46127763,88","42742773,93","45592686,49","4973573613,47"
26,Distrito Federal,"4745919,19","7632480,67","9647203,26","11098732,99","12891719,72","12850125,67","12565646,74","13710857,89","13165106,20",...,"25269773,34","26526196,39","20056592,11","20856249,30","20459325,27","22991567,76","23527050,29","22766952,62","31831917,45","2592422853,56"
27,Total,"408424859,23","613174269,21","664043058,38","686662861,42","715803639,49","752181563,64","764990284,76","750608648,28","752962642,15",...,"1484010417,62","1514160823,72","1477904466,14","1489983146,21","1464196395,75","1441199605,05","1513991196,49","1500612299,36","1687562138,38","172481760138,88"

O motor de leitura padrão do `pandas` (é baseado em C, para ser mais rápido) não suporta essa funcionalidade.

O motor `Python` é mais flexível e consegue lidar com o skipfooter, mas pode ser um pouco mais lento para arquivos muito grandes em comparação com o motor C. Por isso, o pandas usa o motor C por padrão e exige especificar explicitamente engine='python' para funcionalidades como skipfooter.